# Generated by Django 4.0 on 2025-07-07 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'カテゴリ', 'verbose_name_plural': 'カテゴリマスタ'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'コメント', 'verbose_name_plural': 'コメント一覧'},
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name': '商品状態', 'verbose_name_plural': '商品状態マスタ'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'お気に入り', 'verbose_name_plural': 'お気に入り一覧'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '取引メッセージ', 'verbose_name_plural': '取引メッセージ一覧'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': '通知', 'verbose_name_plural': '通知一覧'},
        ),
        migrations.AlterModelOptions(
            name='ntftype',
            options={'verbose_name': '通知種別', 'verbose_name_plural': '通知種別マスタ'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品一覧'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': '商品画像', 'verbose_name_plural': '商品画像一覧'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': '評価', 'verbose_name_plural': '評価一覧'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': '販売状況', 'verbose_name_plural': '販売状況マスタ'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': '取引', 'verbose_name_plural': '取引一覧'},
        ),
        migrations.AlterModelOptions(
            name='transactionstatus',
            options={'verbose_name': '取引状況', 'verbose_name_plural': '取引状況マスタ'},
        ),
        migrations.AddField(
            model_name='status',
            name='purchasable',
            field=models.BooleanField(default=False, verbose_name='購入可能フラグ'),
        ),
        migrations.CreateModel(
            name='StatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='main.status', verbose_name='遷移元ステータス')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='main.status', verbose_name='遷移先ステータス')),
            ],
            options={
                'verbose_name': '販売状況遷移',
                'verbose_name_plural': '販売状況遷移マスタ',
                'unique_together': {('from_status', 'to_status')},
            },
        ),
    ]
