# Generated by Django 4.0 on 2025-07-07 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionStatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('from_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='main.transactionstatus', verbose_name='遷移前ステータス')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='main.transactionstatus', verbose_name='遷移後ステータス')),
            ],
            options={
                'verbose_name': '取引状況遷移',
                'verbose_name_plural': '取引状況遷移マスタ',
            },
        ),
        migrations.AddConstraint(
            model_name='transactionstatustransition',
            constraint=models.UniqueConstraint(fields=('from_status',), name='unique_from_status_only_one_transition'),
        ),
    ]
